[package]
name = "svm-runner-types"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
serde = { workspace = true, features = ["derive"] }
solana-sdk = { workspace = true }
